<?php

/**
 * This is the model base class for the table "post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "post" available as properties of the model,
 * followed by relations of table "post" available as properties of the model.
 *
 * @property integer $post_id
 * @property string $post_text
 * @property string $post_title
 * @property string $post_date
 * @property integer $post_category
 * @property integer $user_id
 *
 * @property Comment[] $comments
 * @property User $user
 * @property Category $postCategory
 */
abstract class BasePost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}
	//Mudança para demonstrar o post_title
	public static function representingColumn() {
		return 'post_title';
	}

	public function rules() {
		return array(
			array('post_text, post_title, post_date, post_category, user_id', 'required'),
			array('post_category, user_id', 'numerical', 'integerOnly'=>true),
			array('post_title', 'length', 'max'=>255),
			array('post_id, post_text, post_title, post_date, post_category, user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'comments' => array(self::HAS_MANY, 'Comment', 'post_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'postCategory' => array(self::BELONGS_TO, 'Category', 'post_category'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'post_id' => Yii::t('app', 'Post'),
			'post_text' => Yii::t('app', 'Post Text'),
			'post_title' => Yii::t('app', 'Post Title'),
			'post_date' => Yii::t('app', 'Post Date'),
			'post_category' => null,
			'user_id' => null,
			'comments' => null,
			'user' => null,
			'postCategory' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('post_text', $this->post_text, true);
		$criteria->compare('post_title', $this->post_title, true);
		$criteria->compare('post_date', $this->post_date, true);
		$criteria->compare('post_category', $this->post_category);
		$criteria->compare('user_id', $this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}